AWSTemplateFormatVersion: 2010-09-09
Description: cloudformation hands-on ap
Parameters:
  AmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  SshKey:
    Description: ssh key name for test server
    Type: String
    Default: seminar
  NamePrefix:
    Description: Prefix for resource Name to identify
    Type: String
    Default: seminar-cfn
  InstanceType:
    Description: demo server instance InstanceType
    Type: String
    Default: t3.micro
  DbMasterUserName:
    Description: demo RDS instance master user name
    Type: AWS::SSM::Parameter::Value<String>
    Default: /seminar/cfn-handson/db-user
  DbPasswordKey:
    Description: ssm parameter key for db password
    Type: String
    Default: /seminar/cfn-handson/db-pass
Resources:
  EC2Ap:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SshKey
      ImageId: !Ref AmiId
      #InstanceType: !Ref InstanceType
      InstanceType: "{{resolve:ssm:/seminar/cfn-handson/ap-size:1}}"
      IamInstanceProfile: !Ref InstanceProfile
      Monitoring: false
      SubnetId:
        Fn::ImportValue: !Sub "${NamePrefix}SubnetIdPublic0"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${NamePrefix}SgIdAp"
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref NamePrefix, ap]]
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash -xv
            DB_HOST="${DB_HOST}"
            DB_USER="${DbMasterUserName}"
            DB_PASSWORD="$(aws ssm get-parameter --name ${DbPasswordKey} --with-decryption --query Parameter.Value --output text --region ${AWS::Region})"
            WP_ACCESS_RANGE=10.0.0.0/255.255.0.0
            WP_PASSWORD=CXQwJxMXT4sB
            yum update -y
            yum install -y httpd mariadb
            amazon-linux-extras install php7.2
            yum install php-mysqlnd
            cat << DDL > /opt/wordpress.ddl
            CREATE DATABASE wordpress;
            GRANT ALL PRIVILEGES ON wordpress.* TO "wordpressuser"@"$WP_ACCESS_RANGE" IDENTIFIED BY "$WP_PASSWORD";
            FLUSH PRIVILEGES;
            EXIT
            DDL
            mysql -h $DB_HOST -u "$DB_USER" --password="$DB_PASSWORD" < /opt/wordpress.ddl
            curl https://wordpress.org/latest.tar.gz | tar -zx
            mv wordpress /var/www/
            function random_string(){
              head -c $(( $1 * 3/2 )) /dev/urandom | \
              base64 | \
              head -c $1
            }
            cat <<EOL > /var/www/wordpress/wp-config.php
            <?php
            // ** MySQL settings - You can get this info from your web host ** //
            /** The name of the database for WordPress */
            define( 'DB_NAME', 'wordpress' );
            /** MySQL database username */
            define( 'DB_USER', 'wordpressuser' );
            /** MySQL database password */
            define( 'DB_PASSWORD', '$WP_PASSWORD' );
            /** MySQL hostname */
            define( 'DB_HOST', '$DB_HOST' );
            /** Database Charset to use in creating database tables. */
            define( 'DB_CHARSET', 'utf8mb4' );
            /** The Database Collate type. Don't change this if in doubt. */
            define( 'DB_COLLATE', '' );
            /**#@+
             * Authentication Unique Keys and Salts.
             *
             * Change these to different unique phrases!
             * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
             * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
             *
             * @since 2.6.0
             */
            define( 'AUTH_KEY',         '$(random_string 64)' );
            define( 'SECURE_AUTH_KEY',  '$(random_string 64)' );
            define( 'LOGGED_IN_KEY',    '$(random_string 64)' );
            define( 'NONCE_KEY',        '$(random_string 64)' );
            define( 'AUTH_SALT',        '$(random_string 64)' );
            define( 'SECURE_AUTH_SALT', '$(random_string 64)' );
            define( 'LOGGED_IN_SALT',   '$(random_string 64)' );
            define( 'NONCE_SALT',       '$(random_string 64)' );
            EOL
            cat <<'EOL' >> /var/www/wordpress/wp-config.php
            /**
             * WordPress Database Table prefix.
             */
            $table_prefix = 'wp_';
            /**
             * For developers: WordPress debugging mode.
             */
            define( 'WP_DEBUG', false );
            /* That's all, stop editing! Happy publishing. */
            /** Absolute path to the WordPress directory. */
            if ( ! defined( 'ABSPATH' ) ) {
                define( 'ABSPATH', dirname( __FILE__ ) . '/' );
            }
            /** Sets up WordPress vars and included files. */
            require_once( ABSPATH . 'wp-settings.php' );
            EOL
            chown -R apache:apache /var/www/wordpress
            sed --in-place  's%^DocumentRoot "/var/www/html"%DocumentRoot "/var/www/wordpress"%' /etc/httpd/conf/httpd.conf
            sed --in-place  's%^<Directory "/var/www">%<Directory "/var/www/wordpress">%' /etc/httpd/conf/httpd.conf
            sed --in-place -r '/^<Directory "\/var\/www\/wordpress">/,/^<\/Directory>/ s/.*AllowOverride None/    AllowOverride All/' /etc/httpd/conf/httpd.conf
            systemctl daemon-reload
            systemctl start httpd
            systemctl enable httpd
          - DB_HOST:
              Fn::ImportValue: !Sub "${NamePrefix}DbEndpoint"
            DB_USER: "{{resolv:ssm:/hoge:1}}"
  Alb:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - Fn::ImportValue: !Sub "${NamePrefix}SgIdAlb"
      Subnets:
        - Fn::ImportValue: !Sub "${NamePrefix}SubnetIdPublic0"
        - Fn::ImportValue: !Sub "${NamePrefix}SubnetIdPublic1"
      Type: application
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref NamePrefix, lb-ap]]
  AlbListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AlbTargetGroup
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
  AlbTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      TargetType: instance
      HealthCheckIntervalSeconds: 6
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: '200'
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'
      Targets:
        - Id: !Ref EC2Ap
      UnhealthyThresholdCount: 3
      VpcId:
        Fn::ImportValue: !Sub "${NamePrefix}VpcId"
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref NamePrefix, tg-ap]]
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RoleAp
  RoleAp:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "ssm-get-parameter"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${DbPasswordKey}"
              -
                Effect: "Allow"
                Action: "kms:Decrypt"
                Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/aws/ssm"
Outputs:
  WordPressUrl:
    Description: URL to access wordpress
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt
          - Alb
          - DNSName

