AWSTemplateFormatVersion: 2010-09-09
Description: cloudformation hands-on vpc
Parameters:
  NamePrefix:
    Description: Prefix for resource Name to identify
    Type: String
    Default: seminar-cfn
  VpcCidr:
    Description: CIDR Block for Vpc
    Type : String
    MinLength: 9
    MaxLength: 18
    Default: 10.0.0.0/16
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref NamePrefix
              - Vpc
Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref Vpc
    Export:
      Name: !Join
        - ''
        - - !Ref NamePrefix
          - VpcId
